spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true  
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream    
